### PR TITLE
feat: [OS-4] [OS-6] Allow users to modify end time and description of connection

### PR DESCRIPTION
**Pull request by sartaj10**
Frontend changes to fix [OS-4](https://esnet-seg.atlassian.net/browse/OS-4) (#304) and [OS-6](https://esnet-seg.atlassian.net/browse/OS-6) (#300)

### CODE REVIEW

**Review by haniotak — APPROVED** [review]
I approve this. I do eventually want to break up detailsEditForm even further so that the schedule editing control set can be re-used in the "New Connection" page.

**Comment by sartaj10** [comment]
@haniotak Do you mean, have a separate component for each FormGroup i.e one for description, one for beginning etc?

**Comment by haniotak** [comment]
> @haniotak Do you mean, have a separate component for each FormGroup i.e one for description, one for beginning etc?

Yes; and each of these to be configurable regarding functions for API callbacks, validation, etc thru props.

**Comment by sartaj10** [comment]
Hmm okay, makes sense. I can look into that eventually

> > @haniotak Do you mean, have a separate component for each FormGroup i.e one for description, one for beginning etc?
> 
> Yes; and each of these to be configurable regarding functions for API callbacks, validation, etc thru props.

**Pull request merged**
